export const ICON = {
  ARROW_CIRCLE_LEFT: 'arrow-circle-left',
  ARROW_CIRCLE_RIGHT: 'arrow-circle-right',
  ARROW_UP_ARROW_DOWN: 'arrow-up-arrow-down',
  ARROW_UP_FROM_BRACKET: 'arrow-up-from-bracket',
  BARS: 'bars',
  BOOKMARK: 'bookmark',
  CALCULATOR: 'calculator',
  CALENDAR: 'calendar',
  CHECK: 'check',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CHEVRON_UP: 'chevron-up',
  CIRCLE_CHECK: 'circle-check',
  CIRCLE_EXCLAMATION: 'circle-exclamation',
  COMMENTS: 'comments',
  CUBE: 'cube',
  ENVELOPE: 'envelope',
  EYE: 'eye',
  FACEBOOK: 'facebook',
  HEART: 'heart',
  HEART_OPEN: 'heart-open',
  INSTAGRAM: 'instagram',
  LINKED_IN: 'linked in',
  MAGNIFYING_GLASS: 'magnifying-glass',
  MESSAGE: 'message',
  PHONE: 'phone',
  PINTEREST: 'pinterest',
  PLAY: 'play',
  SLIDERS: 'sliders',
  STAR: 'star',
  TAG: 'tag',
  TOUR: 'tour',
  TRASH_CAN: 'trash-can',
  TWITTER: 'twitter',
  UP_RIGHT_FROM_SQUARE: 'up-right-from-square',
  USER: 'user',
  VIDEO: 'video',
  XMARK: 'xmark',
  YOUTUBE: 'youtube',
} as const;

export const ICON_COLOR = {
  BLUE: 'font-blue',
  RED: 'font-red',
} as const;

export type Icon = (typeof ICON)[keyof typeof ICON];
export type IconColor = (typeof ICON_COLOR)[keyof typeof ICON_COLOR];
