export const ICON = {
  ARROW_BACK: 'arrow-back',
  ARROW_FORWARD: 'arrow-forward',
  ARROW_RIGHT: 'arrow-right',
  BOOKMARK: 'bookmark',
  CALENDAR: 'calendar',
  CALL: 'call',
  CHECK: 'check',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CLOSE: 'close',
  ERROR: 'error',
  EXPAND: 'expand',
  EXPAND_LESS: 'expand-less',
  EXPAND_MORE: 'expand-more',
  EYE: 'eye',
  FACEBOOK: 'facebook',
  FAVORITE: 'favorite',
  FAVORITE_FILLED: 'favorite-filled',
  FORUM: 'forum',
  INFO: 'info',
  INSTAGRAM: 'instagram',
  IOS_SHARE: 'ios-share',
  LINKED_IN: 'linked in',
  MAIL: 'mail',
  MENU: 'menu',
  MESSAGE: 'message',
  OPEN_IN_NEW: 'open-in-new',
  PERSON: 'person',
  PINTEREST: 'pinterest',
  PLAY: 'play',
  REMOVE: 'remove',
  SEARCH: 'search',
  SELL: 'sell',
  SHARE: 'share',
  STAR: 'star',
  SWAP_VERT: 'swap-vert',
  THREE_D_ROTATION: '3d-rotation',
  TUNE: 'tune',
  TWITTER: 'twitter',
  VIDEO: 'video',
  VIEW_IN_AR: 'view-in-ar',
  YOUTUBE: 'youtube',
} as const;

export type Icon = (typeof ICON)[keyof typeof ICON];
