const DYNAMIC_UTILITIES = {
  BG_GRADIENT: 'bg-gradient',
  BG_PRIMARY_TIER_1: 'bg-primary-tier-1',
  BG_PRIMARY_TIER_2: 'bg-primary-tier-2',
  BG_PRIMARY_TIER_3: 'bg-primary-tier-3',
  BG_PRIMARY_VARIANT_TIER_1: 'bg-primary-variant-tier-1',
  BG_PRIMARY_VARIANT_TIER_2: 'bg-primary-variant-tier-2',
  BG_PRIMARY_VARIANT_TIER_3: 'bg-primary-variant-tier-3',
  BG_SECONDARY: 'bg-secondary',
  BG_SURFACE: 'bg-surface',
  BG_SURFACE_HIGH: 'bg-surface-high',
  BG_SURFACE_LOW: 'bg-surface-low',
  BG_SURFACE_VARIANT: 'bg-surface-variant',
  BG_SURFACE_VARIANT_HIGH: 'bg-surface-variant-high',
  BG_SURFACE_VARIANT_HIGHEST: 'bg-surface-variant-highest',
  BG_SURFACE_VARIANT_LOW: 'bg-surface-variant-low',
  BG_SURFACE_VARIANT_LOWEST: 'bg-surface-variant-lowest',
  BG_TERTIARY: 'bg-tertiary',
  BORDER_PRIMARY_TIER_1: 'border-primary-tier-1',
  BORDER_PRIMARY_TIER_2: 'border-primary-tier-2',
  BORDER_PRIMARY_TIER_3: 'border-primary-tier-3',
  BORDER_PRIMARY_VARIANT_TIER_1: 'border-primary-variant-tier-1',
  BORDER_PRIMARY_VARIANT_TIER_2: 'border-primary-variant-tier-2',
  BORDER_PRIMARY_VARIANT_TIER_3: 'border-primary-variant-tier-3',
  BORDER_SECONDARY: 'border-secondary',
  BORDER_SURFACE: 'border-surface',
  BORDER_SURFACE_HIGH: 'border-surface-high',
  BORDER_SURFACE_LOW: 'border-surface-low',
  BORDER_SURFACE_SAVE: 'border-surface-save',
  BORDER_TERTIARY: 'border-tertiary',
  FONT_PRIMARY_TIER_1: 'font-primary-tier-1',
  FONT_PRIMARY_TIER_2: 'font-primary-tier-2',
  FONT_PRIMARY_TIER_3: 'font-primary-tier-3',
  FONT_PRIMARY_VARIANT_TIER_1: 'font-primary-variant-tier-1',
  FONT_PRIMARY_VARIANT_TIER_2: 'font-primary-variant-tier-2',
  FONT_PRIMARY_VARIANT_TIER_3: 'font-primary-variant-tier-3',
  FONT_SECONDARY: 'font-secondary',
  FONT_SURFACE: 'font-surface',
  FONT_SURFACE_DARK: 'font-surface-dark',
  FONT_SURFACE_LIGHT: 'font-surface-light',
  FONT_SURFACE_VARIANT: 'font-surface-variant',
  FONT_SURFACE_VARIANT_LIGHT: 'font-surface-variant-light',
  FONT_TERTIARY: 'font-tertiary',
} as const;

const BACKGROUND_COLOR = {
  BG_BEIGE: 'bg-beige',
  BG_BLACK: 'bg-black',
  BG_BLUE: 'bg-blue',
  BG_BLUE_DARK: 'bg-blue-dark',
  BG_BLUE_LIGHT: 'bg-blue-light',
  BG_GRAY: 'bg-gray',
  BG_GRAY_DARK: 'bg-gray-dark',
  BG_GRAY_LIGHT: 'bg-gray-light',
  BG_GREEN: 'bg-green',
  BG_RED: 'bg-red',
  BG_WHITE: 'bg-white',
};

const BORDER = {
  BORDER_1: 'border-1',
  BORDER_2: 'border-2',
  BORDER_B: 'border-b',
  BORDER_BLACK: 'border-black',
  BORDER_BLUE: 'border-blue',
  BORDER_BLUE_DARK: 'border-blue-dark',
  BORDER_BLUE_LIGHT: 'border-blue-light',
  BORDER_B_1: 'border-b-1',
  BORDER_B_2: 'border-b-2',
  BORDER_GRAY: 'border-gray',
  BORDER_GRAY_DARK: 'border-gray-dark',
  BORDER_GRAY_LIGHT: 'border-gray-light',
  BORDER_GREEN: 'border-green',
  BORDER_L: 'border-l',
  BORDER_L_1: 'border-l-1',
  BORDER_L_2: 'border-l-2',
  BORDER_R: 'border-r',
  BORDER_RED: 'border-red',
  BORDER_R_1: 'border-r-1',
  BORDER_R_2: 'border-r-2',
  BORDER_T: 'border-t',
  BORDER_T_1: 'border-t-1',
  BORDER_T_2: 'border-t-2',
  BORDER_WHITE: 'border-white',
};

const BOX_SIZING = {
  BORDER_BOX: 'border-box',
  CONTENT_BOX: 'content-box',
};

const DIMENSION = {
  H_0: 'h-0',
  H_1_2: 'h-1/2',
  H_1_3: 'h-1/3',
  H_1_4: 'h-1/4',
  H_2_3: 'h-2/3',
  H_3_4: 'h-3/4',
  H_FULL: 'h-full',
  MAX_W_FULL: 'max-w-full',
  W_0: 'w-0',
  W_1_2: 'w-1/2',
  W_1_3: 'w-1/3',
  W_1_4: 'w-1/4',
  W_2_3: 'w-2/3',
  W_3_4: 'w-3/4',
  W_CONTAINER: 'w-container',
  W_FULL: 'w-full',
};

const DISPLAY = {
  BLOCK: 'block',
  CONTENTS: 'contents',
  FLEX: 'flex',
  GRID: 'grid',
  HIDDEN: 'hidden',
  INITIAL: 'initial',
  INLINE: 'inline',
  INLINE_BLOCK: 'inline-block',
  INLINE_FLEX: 'inline-flex',
};

const FLEXBOX = {
  AXIS1_AROUND: 'axis1-around',
  AXIS1_BETWEEN: 'axis1-between',
  AXIS1_CENTER: 'axis1-center',
  AXIS1_END: 'axis1-end',
  AXIS1_START: 'axis1-start',
  AXIS2_AROUND: 'axis2-around',
  AXIS2_CENTER: 'axis2-center',
  AXIS2_END: 'axis2-end',
  AXIS2_START: 'axis2-start',
  COLUMN: 'column',
  COLUMN_REVERSE: 'column-reverse',
  GAP_1: 'gap-1',
  GAP_1_2: 'gap-1/2',
  GAP_1_4: 'gap-1/4',
  GAP_2: 'gap-2',
  GAP_3_2: 'gap-3/2',
  GAP_3_4: 'gap-3/4',
  GAP_4: 'gap-4',
  GROW: 'grow',
  GROW_NONE: 'grow-none',
  ROW: 'row',
  ROW_REVERSE: 'row-reverse',
  SELF_STRETCH: 'self-stretch',
  SHRINK: 'shrink',
  SHRINK_NONE: 'shrink-none',
  WRAP: 'wrap',
};

const FONT_COLOR = {
  FONT_GRAY: 'font-gray',
  FONT_GRAY_DARK: 'font-gray-dark',
  FONT_GRAY_LIGHT: 'font-gray-light',
  FONT_GREEN: 'font-green',
};

const FONT_FAMILY = {
  FONT_FAMILY_DEFAULT: 'font-family-default',
  FONT_FAMILY_TITLE: 'font-family-title',
};

const FONT_SIZE = {
  FONT_10: 'font-10',
  FONT_12: 'font-12',
  FONT_14: 'font-14',
  FONT_16: 'font-16',
  FONT_18: 'font-18',
  FONT_20: 'font-20',
  FONT_24: 'font-24',
  FONT_28: 'font-28',
  FONT_32: 'font-32',
};

const FONT_WEIGHT = {
  FONT_500: 'font-500',
  FONT_600: 'font-600',
  FONT_700: 'font-700',
};

const MARGIN = {
  MB_1: 'margin-b-1',
  MB_1_2: 'margin-b-1/2',
  MB_1_4: 'margin-b-1/4',
  MB_2: 'margin-b-2',
  MB_3_2: 'margin-b-3/2',
  MB_3_4: 'margin-b-3/4',
  MB_4: 'margin-b-4',
  MB_AUTO: 'margin-b-auto',
  ML_1: 'margin-l-1',
  ML_1_2: 'margin-l-1/2',
  ML_1_4: 'margin-l-1/4',
  ML_2: 'margin-l-2',
  ML_3_2: 'margin-l-3/2',
  ML_3_4: 'margin-l-3/4',
  ML_4: 'margin-l-4',
  ML_AUTO: 'margin-l-auto',
  MR_1: 'margin-r-1',
  MR_1_2: 'margin-r-1/2',
  MR_1_4: 'margin-r-1/4',
  MR_2: 'margin-r-2',
  MR_3_2: 'margin-r-3/2',
  MR_3_4: 'margin-r-3/4',
  MR_4: 'margin-r-4',
  MR_AUTO: 'margin-r-auto',
  MT_1: 'margin-t-1',
  MT_1_2: 'margin-t-1/2',
  MT_1_4: 'margin-t-1/4',
  MT_2: 'margin-t-2',
  MT_3_2: 'margin-t-3/2',
  MT_3_4: 'margin-t-3/4',
  MT_4: 'margin-t-4',
  MT_AUTO: 'margin-t-auto',
  MX_1: 'margin-x-1',
  MX_1_2: 'margin-x-1/2',
  MX_1_4: 'margin-x-1/4',
  MX_2: 'margin-x-2',
  MX_3_2: 'margin-x-3/2',
  MX_3_4: 'margin-x-3/4',
  MX_4: 'margin-x-4',
  MX_AUTO: 'margin-x-auto',
  MY_1: 'margin-y-1',
  MY_1_2: 'margin-y-1/2',
  MY_1_4: 'margin-y-1/4',
  MY_2: 'margin-y-2',
  MY_3_2: 'margin-y-3/2',
  MY_3_4: 'margin-y-3/4',
  MY_4: 'margin-y-4',
  M_1: 'margin-1',
  M_1_2: 'margin-1/2',
  M_1_4: 'margin-1/4',
  M_2: 'margin-2',
  M_3_2: 'margin-3/2',
  M_3_4: 'margin-3/4',
  M_4: 'margin-4',
  M_AUTO: 'margin-auto',
};

const MISC = {
  ALIGN_MIDDLE: 'align-middle',
  BORDER_OVERLAY: 'border-overlay',
  BREAK_WORD: 'break-word',
  INVISIBLE: 'invisible',
  LEADING_DEFAULT: 'leading-default',
  LEADING_WIDE: 'leading-wide',
  LIST_NONE: 'list-none',
  LOWER: 'lower',
  NOT_ALLOWED: 'not-allowed',
  OBJECT_CENTER: 'object-center',
  OBJECT_CONTAIN: 'object-contain',
  OBJECT_COVER: 'object-cover',
  OBJECT_SCALE_DOWN: 'object-scale-down',
  POINTER: 'pointer',
  POINTER_EVENTS: 'pointer-events',
  POINTER_EVENTS_NONE: 'pointer-events-none',
  RATIO_16_9: 'ratio-16/9',
  RATIO_1_1: 'ratio-1/1',
  RATIO_3_2: 'ratio-3/2',
  SCROLLBAR_NONE: 'scrollbar-none',
  SNAP: 'snap',
  SNAP_START: 'snap-start',
  TEXT_CENTER: 'text-center',
  TEXT_LEFT: 'text-left',
  THEME_DARK: 'theme-dark',
  THEME_LIGHT: 'theme-light',
  UNDERLINE: 'underline',
  UNDERLINE_HOVER: 'underline-hover',
  UNDERLINE_NONE: 'underline-none',
  UPPER: 'upper',
  VISIBLE: 'visible',
  WHITESPACE_NOWRAP: 'whitespace-nowrap',
  XY_AUTO: 'xy-auto',
  XY_HIDDEN: 'xy-hidden',
  X_AUTO: 'x-auto',
  X_HIDDEN: 'x-hidden',
  X_SCROLL: 'x-scroll',
  Y_AUTO: 'y-auto',
  Y_HIDDEN: 'y-hidden',
};

const PADDING = {
  PB_1: 'padding-b-1',
  PB_1_2: 'padding-b-1/2',
  PB_1_4: 'padding-b-1/4',
  PB_2: 'padding-b-2',
  PB_3_2: 'padding-b-3/2',
  PB_3_4: 'padding-b-3/4',
  PB_4: 'padding-b-4',
  PL_1: 'padding-l-1',
  PL_1_2: 'padding-l-1/2',
  PL_1_4: 'padding-l-1/4',
  PL_2: 'padding-l-2',
  PL_3_2: 'padding-l-3/2',
  PL_3_4: 'padding-l-3/4',
  PL_4: 'padding-l-4',
  PR_1: 'padding-r-1',
  PR_1_2: 'padding-r-1/2',
  PR_1_4: 'padding-r-1/4',
  PR_2: 'padding-r-2',
  PR_3_2: 'padding-r-3/2',
  PR_3_4: 'padding-r-3/4',
  PR_4: 'padding-r-4',
  PT_1: 'padding-t-1',
  PT_1_2: 'padding-t-1/2',
  PT_1_4: 'padding-t-1/4',
  PT_2: 'padding-t-2',
  PT_3_2: 'padding-t-3/2',
  PT_3_4: 'padding-t-3/4',
  PT_4: 'padding-t-4',
  PX_1: 'padding-x-1',
  PX_1_2: 'padding-x-1/2',
  PX_1_4: 'padding-x-1/4',
  PX_2: 'padding-x-2',
  PX_3_2: 'padding-x-3/2',
  PX_3_4: 'padding-x-3/4',
  PX_4: 'padding-x-4',
  PY_1: 'padding-y-1',
  PY_1_2: 'padding-y-1/2',
  PY_1_4: 'padding-y-1/4',
  PY_2: 'padding-y-2',
  PY_3_2: 'padding-y-3/2',
  PY_3_4: 'padding-y-3/4',
  PY_4: 'padding-y-4',
  P_1: 'padding-1',
  P_1_2: 'padding-1/2',
  P_1_4: 'padding-1/4',
  P_2: 'padding-2',
  P_3_2: 'padding-3/2',
  P_3_4: 'padding-3/4',
  P_4: 'padding-4',
};

const POSITION = {
  ABSOLUTE: 'absolute',
  BOTTOM_0: 'bottom-0',
  BOTTOM_50: 'bottom-1/2',
  FIXED: 'fixed',
  LEFT_0: 'left-0',
  LEFT_50: 'left-1/2',
  RELATIVE: 'relative',
  RIGHT_0: 'right-0',
  RIGHT_50: 'right-1/2',
  STICKY: 'sticky',
  TOP_0: 'top-0',
  TOP_50: 'top-1/2',
  TRANSLATE_X_50: '-translate-x-1/2',
  TRANSLATE_Y_50: '-translate-y-1/2',
};

const RADIUS = {
  RADIUS_1: 'radius-1',
  RADIUS_1_2: 'radius-1/2',
  RADIUS_1_4: 'radius-1/4',
  RADIUS_1_8: 'radius-1/8',
  RADIUS_3_4: 'radius-3/4',
  RADIUS_FULL: 'radius-full',
};

const SHADOW = {
  SHADOW_B_1: 'shadow-b-1',
  SHADOW_B_2: 'shadow-b-2',
  SHADOW_B_3: 'shadow-b-3',
  SHADOW_B_4: 'shadow-b-4',
  SHADOW_B_5: 'shadow-b-5',
  SHADOW_T_1: 'shadow-t-1',
  SHADOW_T_2: 'shadow-t-2',
  SHADOW_T_3: 'shadow-t-3',
  SHADOW_T_4: 'shadow-t-4',
  SHADOW_T_5: 'shadow-t-5',
};

export const CSS_UTILS = {
  ...BACKGROUND_COLOR,
  ...BORDER,
  ...BOX_SIZING,
  ...DIMENSION,
  ...DISPLAY,
  ...DYNAMIC_UTILITIES,
  ...FLEXBOX,
  ...FONT_COLOR,
  ...FONT_FAMILY,
  ...FONT_SIZE,
  ...FONT_WEIGHT,
  ...MARGIN,
  ...MISC,
  ...PADDING,
  ...POSITION,
  ...RADIUS,
  ...SHADOW,
} as const;

export type CSSUtility = (typeof CSS_UTILS)[keyof typeof CSS_UTILS];
