const DYNAMIC_UTILITIES = {} as const;

const BORDER = {
  BORDER_1: 'tide-border-1',
  BORDER_2: 'tide-border-2',
  BORDER_B: 'tide-border-bottom',
  BORDER_BLACK: 'tide-border-black',
  BORDER_BLUE: 'tide-border-blue',
  BORDER_BLUE_DARK: 'tide-border-blue-dark',
  BORDER_BLUE_LIGHT: 'tide-border-blue-light',
  BORDER_B_1: 'tide-border-bottom-1',
  BORDER_B_2: 'tide-border-bottom-2',
  BORDER_GRAY: 'tide-border-gray',
  BORDER_GRAY_DARK: 'tide-border-gray-dark',
  BORDER_GRAY_LIGHT: 'tide-border-gray-light',
  BORDER_GREEN: 'tide-border-green',
  BORDER_L: 'tide-border-left',
  BORDER_L_1: 'tide-border-left-1',
  BORDER_L_2: 'tide-border-left-2',
  BORDER_R: 'tide-border-right',
  BORDER_RED: 'tide-border-red',
  BORDER_R_1: 'tide-border-right-1',
  BORDER_R_2: 'tide-border-right-2',
  BORDER_T: 'tide-border-top',
  BORDER_T_1: 'tide-border-top-1',
  BORDER_T_2: 'tide-border-top-2',
  BORDER_WHITE: 'tide-border-white',
};

const BOX_SIZING = {
  BORDER_BOX: 'tide-box-border',
  CONTENT_BOX: 'tide-box-content',
};

const DIMENSION = {
  H_0: 'tide-height-0',
  H_1_2: 'tide-height-1/2',
  H_1_3: 'tide-height-1/3',
  H_1_4: 'tide-height-1/4',
  H_2_3: 'tide-height-2/3',
  H_FULL: 'tide-height-full',
  MAX_W_FULL: 'tide-max-width-full',
  W_0: 'tide-width-0',
  W_1_2: 'tide-width-1/2',
  W_1_3: 'tide-width-1/3',
  W_1_4: 'tide-width-1/4',
  W_2_3: 'tide-width-2/3',
  W_CONTAINER: 'tide-width-container',
  W_FULL: 'tide-width-full',
};

const DISPLAY = {
  BLOCK: 'tide-display-block',
  CONTENTS: 'tide-contents',
  FLEX: 'tide-display-flex',
  GRID: 'tide-display-grid',
  HIDDEN: 'tide-display-hidden',
  INITIAL: 'initial',
  INLINE: 'tide-display-inline',
  INLINE_BLOCK: 'tide-display-inline-block',
  INLINE_FLEX: 'tide-display-inline-flex',
};

const FLEXBOX = {
  AXIS1_AROUND: 'tide-axis1-around',
  AXIS1_BETWEEN: 'tide-axis1-between',
  AXIS1_CENTER: 'tide-axis1-center',
  AXIS1_END: 'tide-axis1-end',
  AXIS1_START: 'tide-axis1-start',
  AXIS2_AROUND: 'tide-axis2-around',
  AXIS2_CENTER: 'tide-axis2-center',
  AXIS2_END: 'tide-axis2-end',
  AXIS2_START: 'tide-axis2-start',
  COLUMN: 'tide-flex-column',
  COLUMN_REVERSE: 'tide-flex-column-reverse',
  GAP_1: 'tide-gap-1',
  GAP_1_2: 'tide-gap-1/2',
  GAP_1_4: 'tide-gap-1/4',
  GAP_2: 'tide-gap-2',
  GAP_4: 'tide-gap-4',
  GROW: 'tide-flex-grow',
  GROW_NONE: 'tide-grow-none',
  ROW: 'tide-flex-row',
  ROW_REVERSE: 'tide-row-reverse',
  SELF_STRETCH: 'tide-self-stretch',
  SHRINK: 'tide-flex-shrink',
  SHRINK_NONE: 'tide-shrink-none',
  WRAP: 'tide-flex-wrap',
};

const FONT_SIZE = {
  FONT_12: 'tide-font-12',
  FONT_14: 'tide-font-14',
  FONT_16: 'tide-font-16',
  FONT_20: 'tide-font-20',
  FONT_24: 'tide-font-24',
  FONT_32: 'tide-font-32',
};

const FONT_WEIGHT = {
  FONT_400: 'tide-font-400',
  FONT_500: 'tide-font-500',
  FONT_600: 'tide-font-600',
  FONT_700: 'tide-font-700',
};

const MARGIN = {
  MB_1: 'tide-margin-bottom-1',
  MB_1_2: 'tide-margin-bottom-1/2',
  MB_1_4: 'tide-margin-bottom-1/4',
  MB_2: 'tide-margin-bottom-2',
  MB_4: 'tide-margin-bottom-4',
  MB_AUTO: 'tide-margin-bottom-auto',
  ML_1: 'tide-margin-left-1',
  ML_1_2: 'tide-margin-left-1/2',
  ML_1_4: 'tide-margin-left-1/4',
  ML_2: 'tide-margin-left-2',
  ML_4: 'tide-margin-left-4',
  ML_AUTO: 'tide-margin-left-auto',
  MR_1: 'tide-margin-right-1',
  MR_1_2: 'tide-margin-right-1/2',
  MR_1_4: 'tide-margin-right-1/4',
  MR_2: 'tide-margin-right-2',
  MR_4: 'tide-margin-right-4',
  MR_AUTO: 'tide-margin-right-auto',
  MT_1: 'tide-margin-top-1',
  MT_1_2: 'tide-margin-top-1/2',
  MT_1_4: 'tide-margin-top-1/4',
  MT_2: 'tide-margin-top-2',
  MT_4: 'tide-margin-top-4',
  MT_AUTO: 'tide-margin-top-auto',
  MX_1: 'tide-margin-x-1',
  MX_1_2: 'tide-margin-x-1/2',
  MX_1_4: 'tide-margin-x-1/4',
  MX_2: 'tide-margin-x-2',
  MX_4: 'tide-margin-x-4',
  MX_AUTO: 'tide-margin-x-auto',
  MY_1: 'tide-margin-y-1',
  MY_1_2: 'tide-margin-y-1/2',
  MY_1_4: 'tide-margin-y-1/4',
  MY_2: 'tide-margin-y-2',
  MY_4: 'tide-margin-y-4',
  M_1: 'tide-margin-1',
  M_1_2: 'tide-margin-1/2',
  M_1_4: 'tide-margin-1/4',
  M_2: 'tide-margin-2',
  M_4: 'tide-margin-4',
  M_AUTO: 'tide-margin-auto',
};

const MISC = {
  ALIGN_MIDDLE: 'tide-align-middle',
  BORDER_OVERLAY: 'border-overlay',
  BREAK_WORD: 'tide-break-word',
  CURSOR_NOT_ALLOWED: 'tide-cursor-not-allowed',
  CURSOR_POINTER: 'tide-cursor-pointer',
  LEADING_DEFAULT: 'tide-leading-default',
  LEADING_WIDE: 'tide-leading-wide',
  LIST_NONE: 'tide-list-none',
  OBJECT_CENTER: 'tide-object-center',
  OBJECT_CONTAIN: 'tide-object-contain',
  OBJECT_COVER: 'tide-object-cover',
  OBJECT_SCALE_DOWN: 'tide-object-scale-down',
  POINTER_EVENTS: 'tide-pointer-events',
  POINTER_EVENTS_NONE: 'tide-pointer-events-none',
  SCROLLBAR_NONE: 'tide-scrollbar-none',
  SNAP: 'tide-snap',
  SNAP_START: 'tide-snap-start',
  TEXT_CENTER: 'tide-text-center',
  TEXT_LEFT: 'tide-text-left',
  TEXT_TRANSFORM_LOWER: 'tide-text-transform-lower',
  TEXT_TRANSFORM_NONE: 'tide-text-transform-none',
  TEXT_TRANSFORM_UPPER: 'tide-text-transform-upper',
  UNDERLINE: 'tide-underline',
  UNDERLINE_HOVER: 'tide-underline-hover',
  UNDERLINE_NONE: 'tide-underline-none',
  VISIBLE: 'tide-visible',
  VISIBLE_NONE: 'tide-visible-none',
  WHITESPACE_NOWRAP: 'tide-whitespace-nowrap',
  XY_AUTO: 'tide-xy-auto',
  XY_HIDDEN: 'tide-xy-hidden',
  X_AUTO: 'tide-x-auto',
  X_HIDDEN: 'tide-x-hidden',
  X_SCROLL: 'tide-x-scroll',
  Y_AUTO: 'tide-y-auto',
  Y_HIDDEN: 'tide-y-hidden',
};

const PADDING = {
  PB_1: 'tide-padding-bottom-1',
  PB_1_2: 'tide-padding-bottom-1/2',
  PB_1_4: 'tide-padding-bottom-1/4',
  PB_2: 'tide-padding-bottom-2',
  PB_4: 'tide-padding-bottom-4',
  PL_1: 'tide-padding-left-1',
  PL_1_2: 'tide-padding-left-1/2',
  PL_1_4: 'tide-padding-left-1/4',
  PL_2: 'tide-padding-left-2',
  PL_4: 'tide-padding-left-4',
  PR_1: 'tide-padding-right-1',
  PR_1_2: 'tide-padding-right-1/2',
  PR_1_4: 'tide-padding-right-1/4',
  PR_2: 'tide-padding-right-2',
  PR_4: 'tide-padding-right-4',
  PT_1: 'tide-padding-top-1',
  PT_1_2: 'tide-padding-top-1/2',
  PT_1_4: 'tide-padding-top-1/4',
  PT_2: 'tide-padding-top-2',
  PT_4: 'tide-padding-top-4',
  PX_1: 'tide-padding-x-1',
  PX_1_2: 'tide-padding-x-1/2',
  PX_1_4: 'tide-padding-x-1/4',
  PX_2: 'tide-padding-x-2',
  PX_4: 'tide-padding-x-4',
  PY_1: 'tide-padding-y-1',
  PY_1_2: 'tide-padding-y-1/2',
  PY_1_4: 'tide-padding-y-1/4',
  PY_2: 'tide-padding-y-2',
  PY_4: 'tide-padding-y-4',
  P_1: 'tide-padding-1',
  P_1_2: 'tide-padding-1/2',
  P_1_4: 'tide-padding-1/4',
  P_2: 'tide-padding-2',
  P_4: 'tide-padding-4',
};

const POSITION = {
  ABSOLUTE: 'tide-position-absolute',
  FIXED: 'tide-position-fixed',
  RELATIVE: 'tide-position-relative',
  STICKY: 'tide-sticky',
};

const POSITIONING = {
  BOTTOM_0: 'tide-bottom-0',
  LEFT_0: 'tide-left-0',
  RIGHT_0: 'tide-right-0',
  TOP_0: 'tide-top-0',
};

const RADIUS = {
  RADIUS_1: 'tide-radius-1',
  RADIUS_1_2: 'tide-radius-1/2',
  RADIUS_1_4: 'tide-radius-1/4',
  RADIUS_FULL: 'tide-radius-full',
};

const SHADOW = {
  SHADOW_BOTTOM: 'tide-shadow-bottom',
  SHADOW_TOP: 'tide-shadow-top',
};

export const CSS_UTILS = {
  ...BORDER,
  ...BOX_SIZING,
  ...DIMENSION,
  ...DISPLAY,
  ...DYNAMIC_UTILITIES,
  ...FLEXBOX,
  ...FONT_SIZE,
  ...FONT_WEIGHT,
  ...MARGIN,
  ...MISC,
  ...PADDING,
  ...POSITION,
  ...POSITIONING,
  ...RADIUS,
  ...SHADOW,
} as const;

export type CSSUtility = (typeof CSS_UTILS)[keyof typeof CSS_UTILS];
