export type Vehicle = {
  address: string;
  adType: string; // Enumerate
  bunkhouseFloorplan: boolean;
  class: string;
  condition: string;
  dealer: string;
  milesAway: number;
  floorplan: boolean;
  hasHiddenPhone: boolean;
  id: number;
  isUsed: boolean;
  label?: string; // Enumerate
  location: string;
  make: string;
  model: string;
  phone: number;
  price: number;
  stock: number;
  year: number;
  zip: string;
};

export type VehicleNew = {
  ad_attribs: string;
  ad_detail_url: string;
  ad_features: string;
  ad_id: number;
  ad_listing_position: 1;
  category_name: string[];
  city: string;
  city_state_facet: string;
  class_id: string;
  class_name: string;
  company_name: string;
  condition: string[];
  create_date: string;
  create_date_formatted: string;
  customer_id: string;
  dealer_features: string;
  dealer_group_dealer_count: string;
  dealer_group_id: string;
  dealer_group_name: string;
  dealer_id: string;
  dealer_phone: string[];
  dealer_website_url: string;
  description: string;
  id: string;
  is_buynow: string;
  is_featured: string;
  is_premium: string;
  is_toppremium: string;
  latitude: string;
  longitude: string;
  make_facet: string[];
  make_id: string[];
  make_name: string[];
  mfr_serial_num: null;
  model_facet: string[];
  model_name: string[];
  msrp: null;
  phone: string;
  photo_count: number;
  photo_ids: String[];
  price: number;
  rebate: null;
  scheme_code: string;
  seller_type: string;
  state_code: string;
  trim_name: string[];
  website_url: null;
  year: number;
};

export type VehicleRaw = {
  ad_attribs: { raw: string };
  ad_detail_url: { raw: string };
  ad_features: { raw: string };
  ad_id: { raw: number };
  ad_listing_position: 1;
  category_name: { raw: string[] };
  city: { raw: string };
  city_state_facet: { raw: string };
  class_id: { raw: string };
  class_name: { raw: string };
  company_name: { raw: string };
  condition: { raw: string[] };
  create_date: { raw: string };
  create_date_formatted: { raw: string };
  customer_id: { raw: string };
  dealer_features: { raw: string };
  dealer_group_dealer_count: { raw: string };
  dealer_group_id: { raw: string };
  dealer_group_name: { raw: string };
  dealer_id: { raw: string };
  dealer_phone: { raw: string[] };
  dealer_website_url: { raw: string };
  description: { raw: string };
  id: { raw: string };
  is_buynow: { raw: string };
  is_featured: { raw: string };
  is_premium: { raw: string };
  is_toppremium: { raw: string };
  latitude: { raw: string };
  longitude: { raw: string };
  make_facet: { raw: string[] };
  make_id: { raw: string[] };
  make_name: { raw: string[] };
  mfr_serial_num: { raw: null };
  model_facet: { raw: string[] };
  model_name: { raw: string[] };
  msrp: { raw: null };
  phone: { raw: string };
  photo_count: { raw: number };
  photo_ids: { raw: String[] };
  price: { raw: number };
  rebate: { raw: null };
  scheme_code: { raw: string };
  seller_type: { raw: string };
  state_code: { raw: string };
  trim_name: { raw: string[] };
  website_url: { raw: null };
  year: { raw: number };
};
