import {
  faTwitter,
  faInstagram,
  faFacebookF,
  faLinkedinIn,
  faPinterestP,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

import { faHeart as faHeartRegular } from '@fortawesome/free-regular-svg-icons';

import {
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowRightArrowLeft,
  faArrowUpFromBracket,
  faBookmark,
  faCalculator,
  faCalendar,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faComments,
  faCube,
  faEnvelope,
  faEye,
  faHeart,
  faMagnifyingGlass,
  faMessage,
  faPhone,
  faPlay,
  faStar,
  faTag,
  faTimes,
  faTrashAlt,
  faUpRightFromSquare,
  faUser,
  faVideo,
} from '@fortawesome/free-solid-svg-icons';

const icons = [
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowRightArrowLeft,
  faArrowUpFromBracket,
  faBookmark,
  faCalculator,
  faCalendar,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faComments,
  faCube,
  faEnvelope,
  faEye,
  faFacebookF,
  faHeart,
  faHeartRegular,
  faInstagram,
  faLinkedinIn,
  faMagnifyingGlass,
  faMessage,
  faPhone,
  faPinterestP,
  faPlay,
  faStar,
  faTag,
  faTimes,
  faTrashAlt,
  faTwitter,
  faUpRightFromSquare,
  faUser,
  faVideo,
  faYoutube,
];

export { icons };
